### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by rahulkore** [Amanastel/abashed-store-5188#10]
1. Use @Data annotations from `lombok package`  for dynamic getters and setters , won't have to create getters and setters manually for all the parameters in entity classes.
2. Instead of prepared statements in DAO implementations , you could use JPA (Java persistence API) , it gives more flexibility in terms of querying the db.
     - It provides methods such as `findById()` where you won't have to write native sql queries explicitly.
     - Internally JPA uses prepared statements only , so it does the job of creating the corresponding queries for you.
3. good job on separating the DB Util class . [nit] => always close the conn object that you open. 
4. conn object could have been globalized or passed as a reference . 
5. In jpa , no need to create conn objects , it does the job for us . pasting some links for JPA 
    - https://www.baeldung.com/the-persistence-layer-with-spring-data-jpa
    - https://www.baeldung.com/learn-jpa-hibernate
6. good job on creating custom exceptions . 
7. put Use cases classes in service layer where all the business logic must reside. 
8. separate controller , service layer must be present .
9. could remove DBUtil from utility into configuration package and initialize the conn objects using dependency injection. Pasting some useful links for dependency injections below.
    - https://www.baeldung.com/spring-dependency-injection
    - https://medium.com/edureka/what-is-dependency-injection-5006b53af782
 10.  functionality is in working condition so that's good.
 11.  Just focus on the aspects that i have mentioned above , you'll be good to go.
 12. good job on camel casing and meaningful variable names.
 13. Below site has some small projects with different spring boot concepts in it , do go through once  on your own pace.
    - https://www.springboottutorial.com/spring-boot-projects-with-code-examples

**Comment by Amanastel** [comment]
done
